
#端口号
server:
  port: 8888

#数据库链接设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keep
    username: root
    password:

#整合Mybatis
mybatis:
  #  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.blq.forteacher.Entity
  #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml